name: Native Smoke Test
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      task:
        required: true
        type: string
      checkout_repository:
        required: true
        type: string
      checkout_ref:
        required: true
        type: string
jobs:
  native_smoke_test:
    name: ${{ inputs.task }}
    uses: ./.github/workflows/smoke-test.yml
    secrets: inherit
    with:
      project: ${{ inputs.project }}
      task: ${{ inputs.task }}
      type: 'native'
      checkout_repository: ${{ inputs.checkout_repository }}
      checkout_ref: ${{ inputs.checkout_ref }}
